### ISSUE TITLE
use history.replace when removing trailing slash

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#10]
```js
Router(controller, {
        '/tasks': 'tasksOpened',
        '/tasks/:taskId': 'taskSelected'
    }, {
        onlyHash: true
    }
).start();
```

* open `http://localhost:3000/#/tasks/606cd2c2-8505-42c9-b795-21530224cc25` in browser
* manually remove id part but preserving trailing slash (`http://localhost:3000/#/tasks/`) and press enter
* route will automatically remove trailing slash
* press browser back button

Expected: 
* return to `http://localhost:3000/#/tasks/606cd2c2-8505-42c9-b795-21530224cc25`

Actual:
* returns to `http://localhost:3000/#/tasks/` and then removes trailing slash again

Not sure which repo this issue best fits.

**Comment by christianalfoni** [comment]
Thanks for reporting! This is definitely a bug, checking it out now :-)

**Comment by christianalfoni** [comment]
Okay, at least chrome does not seem to trigger the hash change event on trailing slash, which just fudges up the history handling in addressbar.... hm hm

**Comment by christianalfoni** [comment]
Okay, figured it out and cleaned up a lot of code. Thanks for the help, will soon release new version of addressbar :-)

**Comment by christianalfoni** [comment]
Okay, new release of addressbar is published, please try it out :-)

Working on setting up a test environment now to get control of all these edge cases!
