### ISSUE TITLE
introduce `startAfter` option

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#11]
```js
Router(controller, {}, {
    'startAfter': 'appMounted'
})
```

Proposed solution:

Append `startRouter` action to `appMounted` signal chain.

**Comment by Guria** [comment]
Just now I have a workaround for this:
```js
import Router from 'cerebral-router';

export default [
    setLoading,
    [
        get('EmployeeCurrent'), {
            error: [setUserError],
            success: [
                setUser,
                [get('TaskListViewItems'), {
                    error: [],
                    success: [setTasks]
                }]
            ]
        }
    ],
    unsetLoading,
    Router.redirect(location.href)
];
```
If I use `Router.start` instead of `Router.redirect(location.href)` my original location.href wouldn't preserved because it [will be replaced by router](https://github.com/christianalfoni/cerebral-router/blob/master/index.js#L91)

**Comment by christianalfoni** [comment]
I believe this can be handled with the signal being passed on events in next release:

```js
controller.on('signalEnd', function (signal) {
  if (signal.name === 'appMounted') {
    router.start();
  }
});
```
Seems okay?
