### ISSUE TITLE
`start` method not corresponding to it's name

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#13]
In fact router starts to work without call of `start()` method. Sometimes we need to delay actual binding, e.g. made some initialization.
My proposal change `start()` method to `start(routeInitial = true)` and make in it [binding calls](https://github.com/christianalfoni/cerebral-router/blob/master/index.js#L75-L93) and routeInitial action.
Subsequent calls of start shouldn't do bindings again.

**Comment by christianalfoni** [comment]
Yup, I agree it is a bad name and should be changed :-)

Not quite sure what you mean about delaying the binding itself?

**Comment by christianalfoni** [comment]
https://github.com/christianalfoni/cerebral/issues/99

**Comment by Guria** [comment]
resolved in https://github.com/christianalfoni/cerebral-router/commit/b48eb68cefc147b39ba67cfe3a538aa957d7fb8d
