### ISSUE TITLE
Namespace inputs

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-router#16]
Combined with https://github.com/christianalfoni/cerebral/issues/103 this would make the debugger nicer, and the input object in general.

We can argue about params, if they should be contained in a params object, or just on the global input object as they are now.

**Comment by bfitch** [comment]
Screenshot showing a common example of the router `input` "pushing" other input values out of view:
 
![screen shot 2015-09-21 at 12 15 32 am](https://cloud.githubusercontent.com/assets/577208/9995791/e1d91e88-6051-11e5-878a-71ac2a675664.png)

My app specific input `{accessToken: 'efdsafeuEREfddfa13rf'}` is not visible. :smile:

**Comment by bfitch** [comment]
I also like the idea @jeroenverfallie mentioned in Gitter about namespacing router `inputs`. Although it wouldn't help this particular issue, it makes the actions code a little clearer: `input.router.params` indicates clearly *where* those values are coming from. Also just keeps the input object a little "cleaner". Just throwing that out there!

**Comment by christianalfoni** [comment]
Jup, I agree, that seems like the best way to go. In combination with the react-object-inspector it is going to be awesome :)

**Comment by jeroenverfallie** [comment]
They are now under `router`. Yay!
