### ISSUE TITLE
(E2E?) Tests

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-router#18]
We need some tests here, specifically for cross browser testing with ease.

In reference with https://github.com/christianalfoni/cerebral/issues/101

**Comment by christianalfoni** [comment]
The Cerebral-Router does not really do much related to the urls. But we can certainly test how signals are triggered based on the result from `url-mapper`. `addressbar` is the project where url behaviour is run and tested. It uses selenium tests to do so. Though only in chrome :-)

We could have E2E tests here too though, hm... could copy over the selenium test project from `addressbar`. I definitely see value in verifying that the tree projects play well together. Okay... let me do that and we can start building some tests :-)

**Comment by christianalfoni** [comment]
We are covering tests now, not E2E, but in combination with addressbar testing and url-mapper I feel we are covered :-)
