### ISSUE TITLE
Analyse if signals exist at configuration time

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-router#19]
Right now, if you enter a signal name that does not exist, it will throw errors when you match the route.

Would be nice to get warnings when you init the router.

**Comment by christianalfoni** [comment]
Completely agree :-) Will make this part of next version

**Comment by Guria** [comment]
fixed in https://github.com/christianalfoni/cerebral-router/commit/223f9bac6a7d010456670a66a1e6a10cccd37dff
