### ISSUE TITLE
setUrl action sets undefined values as part of url

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#21]
```js
controller.signal(navigatedToModule, ( { module = 'core' }, state ) => {
    state.set(['activeModule', 'name'], module);
} );

Router(controller, {
    '/': 'navigatedToModule',
    '/:module': 'navigatedToModule'
}, {
    onlyHash: true
}).trigger();
```
Navigating by urls works fine, but if we call `navigatedToModule` without arguments url would be set to `/#/undefined`

**Comment by christianalfoni** [comment]
Yes, this is due to a bug in url-mapper. It finds two hits. /#/ and /#/:module , so it chooses the /#/:module where :module is undefined :)

**Comment by Guria** [comment]
I know about two hits. Just think that undefined/null values shouldn't go to url

**Comment by christianalfoni** [comment]
Yeah, though, hm. The thing is that if `/` is not defined it should actually be an invalid url. Maybe we should prevent route change and give a warning in the console about invalid url? If `*` exists it would go there.

**Comment by christianalfoni** [comment]
Ah, wait, I just could not find that route definition... but found it now... Okay. I got clear picture. Hm, by running `navigatedToModule` without arguments you are telling it to go to undefined module really. So it is correct from one perspective. What should happen? Invalid route? Would that not be more confusing really? could throw a warning?

**Comment by christianalfoni** [comment]
We could say: "Route /:module was triggered with missing params"

**Comment by Guria** [comment]
https://github.com/Guria/cerebral-modular/blob/master/app/core/signals.js
https://github.com/Guria/cerebral-modular/blob/master/app/core/actions/checkModuleExists.js
https://github.com/Guria/cerebral-modular/blob/master/app/core/actions/setModule.js

**Comment by Guria** [comment]
Here how i supposed to use it.
It works fine. `this.props.signals.navigatedToModule()` activates `core` module but `undefined appears in url`

**Comment by christianalfoni** [comment]
Hm, but it does run `redirect`?

**Comment by Guria** [comment]
Nope. It would led to infinite loop. In case of `input.module` is `undefined` it filled with default `core` parameter

**Comment by christianalfoni** [comment]
The thing is that you might do: `/:module/:submodule`. You would have a url of `/#//submodule` which would also look weird, hm

**Comment by christianalfoni** [comment]
I am thinking that invalid params should be handled the same way as any invalid url, go to `*`

**Comment by christianalfoni** [comment]
There are basically three situations here:

1. Go to url with valid params and module exists
2. Go to url with valid params and module does not exist
3. Go to url with invalid params

Where 1. and 2. will be handled with signals and 3. will not trigger url at all, but go to `*` if defined. Does that make sense?

**Comment by christianalfoni** [comment]
So in this situation the url would indeed be `/#/` as it just reverts to previous url and no signal is triggered. If you want to handle it, add a `*` url definition.

**Comment by Guria** [comment]
> The thing is that you might do: /:module/:submodule. You would have a url of /#//submodule which would also look weird, hm

Most likely it would be something like this:
```js
routes = {
    '/logout': 'logoutNavigated',
    '/login': 'loginNavigated',
    '/signup': 'signupNavigated',
    '/someList': 'someListNavigated',
    '/someList/:id': 'someListItemNavigated',
    '/': 'coreNavigatedToModule',
    '/:module': 'coreNavigatedToModule'
};
```
```js
[
    [
        'coreAppMounted',
        setUser
    ],
    [
        'coreNavigatedToModule',
        checkModuleExists, {
            success: [setModule],
            error: [redirect('/')]
        }
    ],
    [
        'dashboardMounted',
        () => { console.log('dashboardMounted') }
    ],
    [
        'loginNavigated',
        () => { console.log('loginNavigated') }
    ],
    [
        'logoutNavigated',
        () => { console.log('logoutNavigated') }
    ],
    [
        'signupNavigated',
        () => { console.log('signupNavigated') }
    ],
    [
        'someListNavigated',
        () => { console.log('someListNavigated') }
    ],
    [
        'someListItemNavigated',
        ({ id }) => { console.log('someListItemNavigated: %s', id) }
    ]
    
];
```
---
> So in this situation the url would indeed be /#/ as it just reverts to previous url and no signal is triggered. If you want to handle it, add a * url definition.

Can't figure now how correctly define `*` url in this case. It would special signal with special action which will set `activeModule` to `core`?

**Comment by christianalfoni** [comment]
Ah, yeah, good question :-) If it is wrong param we could pass signal it was supposed to trigger. That way you could verify that it indeed was a wrong parameter on `/:module` and you could trigger an output of `goToDefaultModule` or something? Even set a warning that it did so etc.

**Comment by Guria** [comment]
Current behavior with signal run suits me without any changes. My issue is only that `undefined` string appears in url.
Whenever signal triggered by router it shouldn't change url actually. 
First time we call `this.props.signals.navigatedToModule()` we have `input.module === undefined`.
setUrl action changes url to `/#/undefined`. we navigated somewhere an the press back. At this time router would call `this.props.signals.navigatedToModule({ module: 'undefined' })` and  now `input.module === 'undefined'`. which breaks `checkModuleExists` action.

**Comment by christianalfoni** [comment]
Hm, yeah, but "undefined" would not appear if invalid params would result in a "bad url", going to `*`.

So with suggested fix, this would happen:

1. You trigger `navigatedToModule()` with no arguments
2. Router knows that it expects a module property, but can not find it
3. URL does not change
4. Signal does not trigger
5. If `*` is defined it will trigger that instead
6. Intended route will be passed `/:module` which can be acted upon in `*` signal

So no undefined or weird behaviour :-)

**Comment by Guria** [comment]
describe 6 in detail, please

**Comment by Guria** [comment]
btw, how about `/:module?` syntax :D?

**Comment by Guria** [comment]
Still think that `undefined` should be resolved to empty string in url. So next time url would be parsed correspondent param would also be `undefined` and not `'undefined'`.

All I need is `return url.replace(param, (input.route.params || input)[key] || '');` on https://github.com/christianalfoni/cerebral-router/blob/master/index.js#L63

**Comment by Guria** [comment]
Sorry for insistence. I'll try to protect my point of view again.
Given router config
```js
Router(controller, {
    '/': 'navigatedToModule',
    '/:module': 'navigatedToModule'
}, {
    onlyHash: true
})
```
It says: both `'/'` and `'/:module` bound to `navigatedToModule` signal. When `navigatedToModule` signal triggered latest route definition would be used.

As app author I am take a responsibility to handle a case when `module` parameter wasn't passed to signal.

**Comment by Guria** [comment]
I think I found a solution you would like. See #23 for details.
Given config
```js
Router(controller, {
    '/:module': 'navigatedToModule'
}, {
    onlyHash: true
})
```
call `this.props.signals.navigatedToModule()` would throw an error since resulted url will not match any of registered routes for `navigatedToModule` signal

**Comment by Guria** [comment]
From gitter:
> @Guria Yeah, thanks for the pull  I just have to be certain about this. My tummy tells me that we should not have special scenarios for undefined. If undefined occurs it means that it triggered a signal-route that should not have been triggered in the first place. Tricking the router to display the correct url and have special scenario for it feels... well, not right to be honest. I think a signal-url with missing params should either throw, because you did something that you were not supposed to. Or it should trigger the catch url signal.
I see your point where two different urls points to the same signal, but with the experience so far I think we should not allow two routes pointing to the same signal. It creates complexity and will probably create a lot of weird scenarios. How I would solve your example is:
signal('navigatedHome', ...loadModule);
signal('navigatedToModule', ...loadModule);
```js
Router(controller, {
    '/': 'navigatedHome',
    '/:module': 'navigatedToModule'
}, {
    onlyHash: true
})
```
You use two different signals, but they both trigger the same chain. This is so much safer as we do not implement special logic. It is also more flexible as it will be easier to scale what happens on / vs /:module. They are two different urls and should trigger two different signals... in my opinion of course 
Sorry being difficult here. We have to solve this and we will  But I think it is the smarter choice to restrict rather than handle special scenarios, possibly opening up for more scenarios that also has to be handled. I hope this makes sense, but please, throw examples and scenarios at me and we will get to the bottom of it

**Comment by Guria** [comment]
in total:
* signals must be bound only once
* all params defined in route must be provided to signal
* resulted url must match defined url

updated #23 to meet new requirements
