### ISSUE TITLE
expose method to get url from signalName + parameters

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#22]
We should be able to make traditional links based on routing config since it allows to use `rightClick + copy` or `rightClick + open in new tab` actions.

It could be achieved with method to get url from signalName and parameters. So it would be able to create something like `Link` component @jeroenverfallie mentioned in #14 and without extra router configuration
```jsx
<Link signal="someSignal" args={ { someParam: true } } >
```
 which will render to 
```jsx
<a href="/#/url/param" onClick=(e) = { e.preventDefault(); this.props.signals.someSignal( { someParam: true })}>
```

**Comment by christianalfoni** [comment]
Yeah, this is a good idea :-) It is specific to react though. Would suggest we put this on the `cerebral-react` package.

**Comment by Guria** [comment]
`<Link />` is `cerebral-react` part of course. But, an url should be extracted from router somehow?

**Comment by Guria** [comment]
symmetrical directive for angular would also useful

**Comment by christianalfoni** [comment]
Yeah, hm, have to figure out a good way to do this :-) Probably the signal will just get a new property that is the url it is bound to. But yeah, will solve this. Very nice suggestion indeed!

**Comment by christianalfoni** [comment]
Added to next release issue: https://github.com/christianalfoni/cerebral-router/issues/44

**Comment by Guria** [comment]
#41 address this
