### ISSUE TITLE
update tests

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#27]
* [x] should set payload to input.route
* [x] should set params directly to input
* [x] should throw if resulted url didn't matches a route
* [x] should set correct url with onlyHash option
* [x] should set correct url with baseUrl option
* [x] should set correct url for `*` route
* [x] should set default url store path
* [x] should set custom url store path
* [ ] should match and pass params with query (needs https://github.com/christianalfoni/url-mapper/issues/6)

**Comment by Guria** [comment]
@christianalfoni how about use actual `cerebral` + `cerebral-baobab` packages? Some test will require pretty complicated stub which could be source of bugs itself

**Comment by Guria** [comment]
@christianalfoni current controller stub doesn't run setUrl action added by router. We can change stub so it would be called with stubbed `store.set` method, but I can't find a good way to do it.

**Comment by christianalfoni** [comment]
Hm, yeah, you make a good point here. Lets bring in Cerebral and cerebral-baobab. You want to do it?

**Comment by Guria** [comment]
Yes. I can do it later tonight.

**Comment by christianalfoni** [comment]
Oki cool, lets try to ship this out the door tomorrow. I will be available most of the day :-)

**Comment by Guria** [comment]
I have prepared new setup, but have to spent some time with real world tasks.
I'll complete this task tonight. Sorry for delay, but I think it is safe to ship router with current test setup.

**Comment by christianalfoni** [comment]
Hehe, no worries, I will go through it and give you my thoughts on it too :-)

**Comment by Guria** [comment]
@christianalfoni all except one done. ready to review and merge.

**Comment by christianalfoni** [comment]
Cool, will check this today! Having our project kick off in about 40 min. Been so much planning the last two days.
