### ISSUE TITLE
warn that parameter doesn't affect resulted url?

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#33]
Let assume we have a route /:param for test signal.
And someone call `controller.signals.test({ param: 1, foo: bar })` or `controller.signals.test.getUrl({ param: 1, foo: bar })`
Should we warn that `foo` parameter doesn't affect resulted `url`?

`foo` param value would be lost when triggering from resulted `ur`l.

But it also could be desired behavior:
* `foo` param would be passed to signal by components handler ( eg see suggestion #22) while in the app
* `foo` param would be lost if `url` on app reload, bookmarking, sharing `url`, opening in new tab, etc.

**Comment by christianalfoni** [comment]
Good question! I would suggest not throwing error as it allows you to update the url with different behaviour. That in itself might not be a good idea, but currently we are exploring new grounds here. So think we should allow it until proven confusing :-)

**Comment by Guria** [comment]
Possible solution is `console.info()` while in production.

**Comment by christianalfoni** [comment]
Currently concluding that this behaviour will not confuse developers. If we get a question about it we can implement :)
