### ISSUE TITLE
router shallows query params

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#35]
* config `'/:test', 'testSignal'`
* url `'/test?foo=bar'`
* signal input `{route: {url:"/#/test", path: "/test", params: {test: "test"}, query: {foo: "bar"} }, test: "test"}`
* setUrl action sets url without query

should router preserve query params?
should router pass query params to input like it [stated in comment](https://github.com/christianalfoni/cerebral-router/blob/8daa9987ac5177ebaa3c3f6f3bfd64a466d2a699/index.js#L66) or just leave it in `input.router.query`

**Comment by Guria** [comment]
My suggestion:
* preserve query params
* leave all query params `input.router.query`
* support `'/:test?foo&bar'` syntax to declare that `foo` and `bar` should be put in `input.foo` and `input.bar`
--
* config `'/:test?foo&bar', 'testSignal'`
* url `'/test?foo=bar&bar=baz&baz=foo'`
* signal input `{route: {url:"/#/test?foo=bar&bar=baz&baz=foo", path: "/test", params: {test: "test"}, query: {foo: "bar", bar: "baz", baz: "foo"} }, test: "test", foo: "bar", bar: "baz"}`
* setUrl action sets `'/test?foo=bar&bar=baz&baz=foo'`
* `testSignal({test: "test", foo: "bar", bar: "baz"})` sets  `'/test?foo=bar&bar=baz'` url

**Comment by christianalfoni** [comment]
This is a very interesting suggestion, though it requires a bit of trickery to accomplish. The reason we put the params on the input is to support firing off the signal manually. So matching params with signal payload. Query is not really related to firing off a signal manually, its like a "relic" of the url, so I think it belongs inside the `route` property.

That said, it might be an idea to expose queries the same way as params. If not I would suggest using `input.query` to expose those. Manually defining them in the url definition is quite a bit of extra complexity, and I think we easily get away with a convention here.

What do you think?

**Comment by Guria** [comment]
did you saw #40?

**Comment by Guria** [comment]
My suggestion stays the same. Defined query params should be exposed, others if present stays only in `input.route.query`

**Comment by Guria** [comment]
My new suggestion: don't run `getUrl` if triggered from `addressbar`.
After christianalfoni/url-mapper/issues/7 released we can reuse original url.
Let fix shallowing and leave query inside `input.route.query` for now.
