### ISSUE TITLE
payload.url seems useless in current setup

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#36]
https://github.com/christianalfoni/cerebral-router/blob/8daa9987ac5177ebaa3c3f6f3bfd64a466d2a699/index.js#L52

* `payload.url` always undefined when triggered from url
* `payload.url` could be set within signal call but its value never used

**Comment by Guria** [comment]
if `url-mapper` would provide url in payload(https://github.com/christianalfoni/url-mapper/issues/7) router can use it to check that url reconstructed from parameters is the same.
see also #35 for use case when checking original url would be possible

**Comment by christianalfoni** [comment]
Hm, is it undefined? Could you elaborate a bit, I can not reproduce it as undefined?

**Comment by Guria** [comment]
see #40

**Comment by Guria** [comment]
`url-mapper` doesn't provide `url` to callback at the moment. So on [this line of code](https://github.com/christianalfoni/cerebral-router/blob/8daa9987ac5177ebaa3c3f6f3bfd64a466d2a699/index.js#L52) it `undefined`. `url` calculated and set at [very end of function](https://github.com/christianalfoni/cerebral-router/blob/8daa9987ac5177ebaa3c3f6f3bfd64a466d2a699/index.js#L103) and don't uses original `url`

**Comment by Guria** [comment]
this issue related to #37. Issue resolved in #41 which already part of #40
