### ISSUE TITLE
router could break signal chain

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#37]
Let assume developer used `url`, `path`, `params` or `query` key in input. [Chain inputs would be broken](https://github.com/christianalfoni/cerebral-router/blob/8daa9987ac5177ebaa3c3f6f3bfd64a466d2a699/index.js#L51-L60) once router added to project.
Also this keys can't be used as keys for route definitions.

**Comment by christianalfoni** [comment]
Router now uses "route" property on input. So this is solved?

**Comment by Guria** [comment]
nope see #41

**Comment by Guria** [comment]
Issue description contains a link to problem code. Issue resolved in #41 which already part of #41
