### ISSUE TITLE
redundant strip off baseUrl

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#39]
https://github.com/christianalfoni/cerebral-router/blob/285c9c36dd3e73507e137ffa06836918246e0b20/index.js#L103
seems redundant since url in this place newer contains baseUrl. Could break app if will accidentally match with part of constructed url.

**Comment by christianalfoni** [comment]
Hm, can not quite see how url never could contain baseUrl? location.pathname may contain baseUrl and need to remove it?
