### ISSUE TITLE
es6 specific syntax

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#43]
Function.name is part of ES6 with poor browser support

https://github.com/christianalfoni/cerebral-router/commit/8384260bab394aa73de70a2332e557013eb4e684#diff-168726dbe96b3ce427e7fedce31bb0bcR28

**Comment by christianalfoni** [comment]
If I understand correctly this can be closed, please reopen if more discussion is needed

**Comment by Guria** [comment]
it solved in #40 and would be closed automatically on merge
