### ISSUE TITLE
fix onlyHash and baseUrl behavior 

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-router#46]
[test for `onlyHash` option](https://github.com/christianalfoni/cerebral-router/blob/master/tests/test.js#L249-L268) was written for current behavior. But it seems wrong.

`/test` url shouldn't match `/:param` route if `onlyHash` option enabled.

> onlyHash is intended as "only treat url definitions behind the hash, if exists"... so should not match url paths before the hash

> onlyHash without baseUrl means baseUrl="/". There is not check for baseUrl now, none of the routes will trigger if it is wrong. That could be a good addition, throw an error if baseUrl is not in the url

**Comment by christianalfoni** [comment]
Jup, agreed, this is fixed in tests on next released. The test fails if hash is not included in the url
