### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral-router#5]
Maybe we should allow for an option that prevents the router from trigger the initial route when Cerebral runs in devmode? So that not each refresh produces a signal on the current route. I believe it will make it a bit easier to develop.

```js
Router(controller, {

}, {
  preventInitialRoute: true
}).start();
```

Or something....

**Comment by jeroenverfallie** [comment]
Is there a scenario where you'd want to produce a new signal? I can't immediatly think of one, so perhaps instead of making it an optional 'disable' you could opt for an optional 'enable'. 

ie. detect for devmode, and prevent by default, enable optionally.

```
Router(controller, {

}, {
  dontPreventInitialRoute: true
}).start();
```

**Comment by christianalfoni** [comment]
Hm hm, I have been thinking about this some more and it is a bit difficult to reason about different behaviours depending on environment. 

I think it might be better to explicitly just do it:

```js
var router = Router(controller, {
  ...
});

if (isProduction) {
  router.start();
}
```

Start really just takes current url and maps it, it does not actually start the router. Hm, maybe give it a better name.
