### ISSUE TITLE
at start and after signal, run custom actions

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral-router#6]
```js
Router(controller, {

}, {
  signalStart: [customAction],
  signalEnd: [customAction2]
});
```

Inject these actions

**Comment by jolafrite** [comment]
Yeah I like this proposal be maybe can add a way to disable a special action per route

ex:
```javascript
Route(controller, {
    '/': 'homeOpened',
    '/users': {
        signal: 'usersOpened',
        disableSignalEnd: ['unsetLoading']
    }
}, {
    signalStart: [setLoading],
    signalEnd: [setPageTitle, unsetLoading]
}
```

**Comment by christianalfoni** [comment]
Hi @jolafrite,

I think this moves us a bit too much in the "configuration" path, rather than "implementation" path. Cerebrals power is in its functional composition. Configuration kinda locks you down, but just adding actions to the signals in question gives you flexibility.

As @garth also mentioned, ut is very unlikely that you want the same action to run on all your routes. Also each route probably has its own loader, like "loading messages" and "loading message", maybe even multiple loaders.

So the configuration will quickly get out of hand as it can not cover all the use cases, but just using actions certainly will handle all of them.

I have given this more thought and I think we should hold on to see more conventions etc. Though this suggestion can reduce some code, it also reduces flexibility and readability. So yeah, I think I have to be a bit stubborn on this one for now.

That said, of course I will keep this open and as we get more experience and input from other devs  maybe we will come up with an even better solution :-)

**Comment by christianalfoni** [comment]
Okay, cleaning up a bit so  will close this for now
