### ISSUE TITLE
Should cerebral-router support document.title?

### ISSUE THREAD

**Issue by grigio** [christianalfoni/cerebral-router#7]
I mean if `state.get('title', 'My page')` is present should also update the document.title on change.

**Comment by christianalfoni** [comment]
Hm, we could allow for that. It already has the special "url" state that is protected, could also have a "title". I think it is a good idea

**Comment by jeroenverfallie** [comment]
It would be a fine idea for static titles, but there's many cases where your title would depend on a param in your url for example: `/board/192` -> `Foo - Board`

In this case, where would you place the logic to define what the dynamic title would be? 
Imo the router configuration is not a good place for this.

I prefer keeping my own property in the state that defines the title, and use https://github.com/gaearon/react-document-title which gives me some more control when dealing with nested routing. For example, `Page - Sitename`, in the case of the router handling this, you'd need to repeat your ` - Sitename` over and over, or write extra logic for it.

**Comment by idream3** [comment]
I am not using Cerebral-router, but I use a factory to set document title and I really like it.

**Comment by christianalfoni** [comment]
Hi again, yeah, the only thing we miss out on is that the title updates when remembering state. Though as @jeroenverfallie is hinting to here is that a component could be responsible for setting the document.title in its "componentDidUpdate" method, or actually where you decide what page to render.

I am starting to think about how services might have a larger role here. Where we want to make effects outside an action a service might be the best way to go. So we would have a "services.title". Using that service to set a title would ensure it working in all scenarios.

Also services.interval is a goo candidate. Let me experiment a bit. But for now, I would say use state and use a component to change the document.title.

**Comment by christianalfoni** [comment]
Cleaning up a bit and will leave this for now as there are good solutions already
